version: 2

jobs:
  run_tests:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run: |
          cd 1_JUnit_Mockito
          mvn test
      - run: |
          cd 2_BDD/TransportMachinesApp/
          mvn test

workflows:
  version: 2
  all:
    jobs:
      - run_tests:
          filters:
            branches:
              only: main
