version: 2

jobs:
  run_tests:
      docker:
      - image: circleci/openjdk:11
      steps:
      - checkout
      - run: |
          cd lab_1_3_JUnit_Mockito
          mvn test
          cd lab_4_BDD/TransportMachinesApp/
          mvn test
          
workflows:
  version: 2
  all:
    jobs:
    - run_tests:
        filters:
          branches:
            only: master

