orbs: 
  maven: circleci/maven@1.3.0
version: 2.1
workflows:
  maven_test:
    jobs:
      - working_directory: '../lab_1_3_JUnit_Mockito'
      - maven/test:
          command: '-X clean'

# Define the jobs we want to run for this project
# jobs:
#   build:
#     docker:
#       - image: ubuntu:20.04
#     steps:
#       - checkout
#       - run: 
#           command: |
#               mvn clean package
#   test:
#     docker:
#       - image: ubuntu:20.04
#     steps:
#       - checkout
#       - run: 
#           command: |
#               mvn test

# # Orchestrate our job run sequence
# workflows:
#   build_and_test:
#     jobs:
#       - build
#       - test
