# version: 2.0

# jobs:
#   build:
#     docker:
#       - image: cimg/openjdk:17.0.1
#         auth:
#           username: mydockerhub-user
#           password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
#     steps:
#       - checkout
#       - run: ../lab_1_3_JUnit_Mockito/mvn package

orbs: 
  maven: circleci/maven@1.3.0
version: 2.1

## Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: ubuntu:20.04
    steps:
      - run: 
          command: |
              ls -la ../
              echo $pwd
              cd ~/../lab_1_3_JUnit_Mockito
              mvn clean package
  test:
    docker:
      - image: ubuntu:20.04
    steps:
      - run: 
          command: |
              cd ~/../lab_1_3_JUnit_Mockito
              mvn test

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
