version: 2.0
description: |
  Checkout, build, test, and upload test results for a Maven project.
executor: <<parameters.executor>>
parameters:
  app_src_directory:
    description: Useful when the source of your maven project is nott in the root directory of your git repo. Supply the name of the directory or relative path of the directory containing your source code.
    type: string
    default: '/lab_1_3_JUnit_Mockito/'
  executor:
    description: The name of custom executor to use
    type: executor
    default: default
  command:
    description: The maven command to run.
    type: string
    default: verify
  test_results_path:
    description: The path to the test results.
    type: string
    default: target/surefire-reports
  settings_file:
    description: Specify a custom settings file to use (optional)
    type: string
    default: ""
  maven_command:
    description: Specify a custom path for invoking maven
    type: string
    default: mvn

jobs:
  build:
    docker: 
      - image: ubuntu:20.04
    steps:
      - checkout
      - steps:
          settings_file: << parameters.settings_file >>
          app_src_directory: << parameters.app_src_directory >>
          maven_command: << parameters.maven_command >>
          steps:
            - run:
                name: Run Tests
                working_directory: << parameters.app_src_directory >>
                command: |
                  if [ -n "<< parameters.settings_file >>" ]; then
                    set -- "$@" --settings "<< parameters.settings_file >>"
                  fi
                  << parameters.maven_command >> << parameters.command >> "$@"
      - process_test_results:
          test_results_path: << parameters.test_results_path >>


# # version: 2.0

# # jobs:
# #   build:
# #     docker:
# #       - image: cimg/openjdk:17.0.1
# #         auth:
# #           username: mydockerhub-user
# #           password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
# #     steps:
# #       - checkout
# #       - run: ../lab_1_3_JUnit_Mockito/mvn package

# orbs: 
#   maven: circleci/maven@1.3.0
# version: 2.1

# ## Define the jobs we want to run for this project
# jobs:
#   build:
#     docker:
#       - image: ubuntu:20.04
#     steps:
#       - attach_workspace:
#           at: . # relative path to our working directory
#       - run: 
#           command: |
#               ls -la ~/project
#               ls -la ../../bin/bash
#               cd ../../ && whereis Dockerfile
#               echo $pwd
#               cd ~/../lab_1_3_JUnit_Mockito
#               mvn clean package

#   test:
#     docker:
#       - image: ubuntu:20.04
#     steps:
#       - attach_workspace:
#           at: . # relative path to our working directory
#       - run: 
#           command: |
#               cd ~/../lab_1_3_JUnit_Mockito
#               mvn test

# # Orchestrate our job run sequence
# workflows:
#   build_and_test:
#     jobs:
#       - build
#       - test
